# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tf_idf',
                'doc_host': 'https://cooperrc.github.io',
                'git_url': 'https://github.com/cooperrc/tf_idf',
                'lib_path': 'tf_idf'},
  'syms': {'tf_idf.core': {'tf_idf.core.foo': ('core.html#foo', 'tf_idf/core.py')}}}
